/* Host-side test: BearSSL TLS client against the local fixture server.
 *
 * The REAL BearSSL sources (third_party/bearssl/src) + prebuilt trust
 * anchors (apps/browser/tls/tas_testca.inc, generated by `brssl ta`).
 * Run: make test-tls (runner starts tests/browser_site/tls_serve.py).
 * Usage: tls_test <ip> <port>  (fixture: 127.0.0.1 8772)
 *
 * Cases:
 *  1. trust anchors load (TAs_NUM == 1, RSA key present)
 *  2. full handshake + GET /redir -> 302 + Location (valid chain, SNI/IP ok)
 *  3. empty trust store -> handshake MUST fail (no silent trust)
 *  4. wrong hostname -> handshake MUST fail (SAN/CN check enforced)
 *  5. far-future injected time -> handshake MUST fail (expiry enforced)
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>

#include "bearssl.h"

#include "tas_testca.inc"

static int fails = 0;

#define CHECK(cond, name) do { \
	if (cond) { printf("PASS %s\n", name); } \
	else { printf("FAIL %s\n", name); fails++; } \
} while (0)

static int tcp_connect(const char *ip, int port)
{
	int fd;
	struct sockaddr_in sa;

	fd = socket(AF_INET, SOCK_STREAM, 0);
	if (fd < 0)
		return -1;
	memset(&sa, 0, sizeof sa);
	sa.sin_family = AF_INET;
	sa.sin_port = htons((unsigned short)port);
	if (inet_pton(AF_INET, ip, &sa.sin_addr) != 1) {
		close(fd);
		return -1;
	}
	if (connect(fd, (struct sockaddr *)&sa, sizeof sa) < 0) {
		close(fd);
		return -1;
	}
	return fd;
}

static int sock_read(void *ctx, unsigned char *buf, size_t len)
{
	int fd = *(int *)ctx;
	ssize_t r = recv(fd, buf, len, 0);
	if (r <= 0)
		return -1;
	return (int)r;
}

static int sock_write(void *ctx, const unsigned char *buf, size_t len)
{
	int fd = *(int *)ctx;
	size_t off = 0;

	while (off < len) {
		ssize_t w = send(fd, buf + off, len - off, 0);
		if (w <= 0)
			return -1;
		off += (size_t)w;
	}
	return (int)off;
}

/* Drive one connection: reset with given name/time/TAs, send req (or NULL
 * to only handshake), collect response. Returns engine error (0 = ok). */
static int run_session(const char *ip, int port, const char *hostname,
		const br_x509_trust_anchor *tas, size_t num_ta,
		int set_future_time,
		const char *req, char *resp, size_t resp_cap,
		size_t *resp_len)
{
	static unsigned char iobuf[BR_SSL_BUFSIZE_BIDI];
	br_ssl_client_context sc;
	br_x509_minimal_context xc;
	br_sslio_context ioc;
	int fd, err;
	const char *get_root = "GET /redir HTTP/1.0\r\nHost: x\r\n\r\n";

	*resp_len = 0;
	fd = tcp_connect(ip, port);
	if (fd < 0)
		return -999;
	br_ssl_client_init_full(&sc, &xc, tas, num_ta);
	br_ssl_engine_set_buffer(&sc.eng, iobuf, sizeof iobuf, 1);
	if (set_future_time) {
		time_t now = time(NULL);
		unsigned long days = (unsigned long)(now / 86400) + 719528UL
			+ 4000UL;
		br_x509_minimal_set_time(&xc, days, 0);
	}
	br_ssl_client_reset(&sc, hostname, 0);
	err = br_ssl_engine_last_error(&sc.eng);
	if (err != 0) {
		close(fd);
		return err;
	}
	br_sslio_init(&ioc, &sc.eng, sock_read, &fd, sock_write, &fd);
	if (req == NULL)
		req = get_root;
	if (br_sslio_write_all(&ioc, req, strlen(req)) < 0) {
		err = br_ssl_engine_last_error(&sc.eng);
		close(fd);
		return err == 0 ? -998 : err;
	}
	br_sslio_flush(&ioc);
	for (;;) {
		int r;
		if (*resp_len >= resp_cap)
			break;
		r = br_sslio_read(&ioc, resp + *resp_len,
			resp_cap - *resp_len);
		if (r < 0)
			break;
		*resp_len += (size_t)r;
	}
	err = br_ssl_engine_last_error(&sc.eng);
	br_sslio_close(&ioc);
	close(fd);
	/* Clean shutdown (close_notify + TCP close) also surfaces as
	 * read error with engine error 0. Accept that as success when
	 * we got a full HTTP response. */
	if (err == 0 || (err == BR_ERR_IO && *resp_len > 0))
		return 0;
	return err;
}

int main(int argc, char **argv)
{
	const char *ip = "127.0.0.1";
	int port = 8772;
	char resp[65536];
	size_t resp_len;
	int err;

	if (argc >= 3) {
		ip = argv[1];
		port = atoi(argv[2]);
	}

	/* 1. anchors */
	CHECK(TAs_NUM == 1, "ta count == 1 (test CA)");
	CHECK(TAs[0].pkey.key_type == BR_KEYTYPE_RSA, "ta key is RSA");
	CHECK(TAs[0].dn.len > 0, "ta DN present");

	/* 2. happy path (DNS name: BearSSL matches dNSName SANs only) */
	memset(resp, 0, sizeof resp);
	err = run_session(ip, port, "localhost", TAs, TAs_NUM, 0,
		NULL, resp, sizeof resp - 1, &resp_len);
	CHECK(err == 0, "handshake + GET ok");
	if (err != 0)
		printf("  engine err=%d\n", err);
	CHECK(resp_len > 0 && strstr(resp, "302") != NULL,
		"GET /redir -> 302");
	CHECK(strstr(resp, "Location: /page2.html") != NULL,
		"redirect target /page2.html");

	/* 3. empty trust store must fail */
	err = run_session(ip, port, "127.0.0.1", NULL, 0, 0,
		NULL, resp, sizeof resp - 1, &resp_len);
	CHECK(err != 0, "empty trust store rejected");
	printf("  (err=%d, want !=0)\n", err);

	/* 4. wrong hostname must fail */
	err = run_session(ip, port, "wrong.invalid", TAs, TAs_NUM, 0,
		NULL, resp, sizeof resp - 1, &resp_len);
	CHECK(err != 0, "wrong hostname rejected");
	printf("  (err=%d, want !=0)\n", err);

	/* 5. far-future time must fail (cert expired by then) */
	err = run_session(ip, port, "localhost", TAs, TAs_NUM, 1,
		NULL, resp, sizeof resp - 1, &resp_len);
	CHECK(err != 0, "expired-by-future-time rejected");
	printf("  (err=%d, want !=0)\n", err);

	if (fails == 0)
		printf("ALL TLS TESTS PASS\n");
	else
		printf("%d TLS TEST(S) FAILED\n", fails);
	return fails != 0;
}
